const ns='http://www.w3.org/2000/svg',sensors=document.querySelector('#sensors'),eventLayer=document.querySelector('#event'),angle=document.querySelector('#angle'),status=document.querySelector('#status');let timers=[];
function el(tag,attrs,parent){const n=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);parent.append(n);return n}
const dots=[];for(let c=0;c<8;c++){el('line',{x1:100+c*80,x2:100+c*80,y1:115,y2:370,stroke:'#849cac','stroke-width':1},sensors);for(let r=0;r<6;r++)dots.push(el('circle',{cx:100+c*80,cy:120+r*47,r:5,fill:'#ddebf0',stroke:'#53788b'},sensors))}
function clear(){timers.forEach(clearTimeout);timers=[];eventLayer.replaceChildren();dots.forEach(d=>d.setAttribute('fill','#ddebf0'))}
function run(hit){clear();const x=380,y=250,a=Number(angle.value)*Math.PI/180,dx=Math.sin(a),dy=Math.cos(a);el('line',{x1:x-dx*270,y1:y-dy*270,x2:x+dx*180,y2:y+dy*180,stroke:hit?'#f8dd87':'#a52d5b','stroke-width':3,'stroke-dasharray':'8 7'},eventLayer);if(!hit){status.textContent='微中子直接穿過冰層，沒有在這次示範中產生可記錄的光。這是一般情況。';return}el('circle',{cx:x,cy:y,r:8,fill:'#fff4bd'},eventLayer);el('path',{d:`M${x} ${y} L${x+dx*135-dy*80} ${y+dy*135+dx*80} L${x+dx*135+dy*80} ${y+dy*135-dx*80} Z`,fill:'#6ce8ff','fill-opacity':.3},eventLayer);dots.forEach((d,i)=>{const dist=Math.hypot(Number(d.getAttribute('cx'))-x,Number(d.getAttribute('cy'))-y);timers.push(setTimeout(()=>d.setAttribute('fill','#75efff'),Math.round(dist*3))) });status.textContent='這次指定一次作用：產生帶電粒子與光訊號，附近感光器依距離先後亮起。真實重建需分析到達時間、亮度及冰的性質。'}
angle.addEventListener('input',()=>{document.querySelector('#angle-value').textContent=angle.value+'°';clear();status.textContent='方向已改變。請選擇直接穿過，或示範一次作用。'});document.querySelector('#pass').onclick=()=>run(false);document.querySelector('#hit').onclick=()=>run(true);document.querySelector('#reset').onclick=()=>{clear();angle.value=20;document.querySelector('#angle-value').textContent='20°';status.textContent='感光器等待光訊號。選一種情況開始。'};

// Decorative particles: directions and speeds are artistic, not measured flux.
(()=>{const canvas=document.querySelector('#neutrino-bg'),ctx=canvas.getContext('2d'),toggle=document.querySelector('#motion-toggle'),reduce=matchMedia('(prefers-reduced-motion: reduce)');let w=0,h=0,particles=[],paused=reduce.matches,frame=0,last=0;function resize(){w=innerWidth;h=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);particles=Array.from({length:w<600?22:42},()=>make(true));draw(0)}function make(initial){const a=Math.random()*Math.PI*2,s=18+Math.random()*28;return{x:Math.random()*w,y:initial?Math.random()*h:-20,vx:Math.cos(a)*s,vy:Math.sin(a)*s,len:12+Math.random()*25}}function draw(dt){ctx.clearRect(0,0,w,h);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.x< -50)p.x=w+30;if(p.x>w+50)p.x=-30;if(p.y< -50)p.y=h+30;if(p.y>h+50)p.y=-30;const speed=Math.hypot(p.vx,p.vy);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x-p.vx/speed*p.len,p.y-p.vy/speed*p.len);ctx.strokeStyle='rgba(110,31,34,0.13)';ctx.lineWidth=.8;ctx.stroke();ctx.beginPath();ctx.arc(p.x,p.y,1.5,0,Math.PI*2);ctx.fillStyle='rgba(184,134,58,0.25)';ctx.fill()}}function tick(t){draw(last?Math.min((t-last)/1000,.05):0);last=t;frame=requestAnimationFrame(tick)}function sync(){cancelAnimationFrame(frame);last=0;toggle.textContent=paused?'開啟背景動畫':'暫停背景動畫';toggle.setAttribute('aria-pressed',String(paused));if(!paused&&!document.hidden)frame=requestAnimationFrame(tick)}toggle.onclick=()=>{paused=!paused;sync()};reduce.addEventListener('change',e=>{paused=e.matches;sync()});document.addEventListener('visibilitychange',sync);addEventListener('resize',resize);resize();sync()})();
